---
title: "ChangeLog - Bongo"
author: "Tim van der Stap"
date: "8/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CHANGELOG

All notable changes to this project will be documented in this file. This document lists all of the data tidying and transformations as applied to the raw file `Zoop Bongo Isotopes_IYS_Dry Weight_Mar31.xlsx`. Manual changes to the raw data file are described here, any scripts used to aid in data tidying can be found in `data_wrangle_bongo.Rmd` on GitHub [here](). 

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

## [1.0.0] - 2021-04-21

### Changed
* For sampleID `Z383` the value in the `tissue` column has been changed to `whole` (as per pers. comm. with Brian H.)
* For sampleID `SS106` the value in the `lifeStage` column has been changed from `CV` to `adult` (as per comm. with Natalie Mahara). `CV` describes a life stage of copepodites, and SS106 is not a copepoda but E. pacifica.
* For sampleID `SS107` the value in the `lifeStage` column has been changed from `CV` to `NA`. This sample refers to Radiolarians, and the `CV` life stage is only applicable to copepodites. 

### Data limitations

The biometric measurements related to sample SS122 is removed from the Standardized Data published to the Ocean Biodiversity Information System (OBIS). The reason for this is that the recorded species `Jellyfish, radiolarians, chaetognath` does not have a common kingdom, and therefore could not be assigned a WoRMS URN. 